services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env # Loads variables from .env into the service's environment
    volumes:
      - .:/usr/src/app # Mounts local code into the container for live reloading
      - /usr/src/app/node_modules # Anonymous volume to prevent local node_modules from overwriting container's
      - /usr/src/app/.next # Anonymous volume for Next.js build cache
    depends_on:
      - postgres_db # Ensures PostgreSQL starts before Next.js

  postgres_db:
    image: postgres:16-alpine
    env_file:
      - .env # Loads variables from .env into the service's environment
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

volumes:
  postgres_data: # Named volume for data persistencesho